# Generated by Django 4.0.4 on 2022-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64, verbose_name='street')),
                ('city', models.CharField(max_length=32, verbose_name='city')),
                ('zipcode', models.CharField(max_length=10, verbose_name='zipcode')),
                ('email', models.CharField(max_length=32, verbose_name='e-mail address')),
                ('phone', models.CharField(max_length=32, verbose_name='phone number')),
                ('employ_id', models.CharField(max_length=10, verbose_name='employ id')),
                ('corporation_name', models.SmallIntegerField(choices=[(1, 'D&G Tax Law'), (2, 'The Acrobatic Accountants LLC'), (3, 'Cafe Msica'), (4, 'Artisan Recording'), (5, 'New York Man'), (6, 'Dreamlike Moustaches'), (7, 'Swift River Sports'), (8, 'The Big Apple Cocktail Company'), (9, 'Pouring Palaces'), (10, 'Schmalzy Pet')], verbose_name='corporation name')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coupon Rate')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64, verbose_name='street')),
                ('city', models.CharField(max_length=32, verbose_name='city')),
                ('zipcode', models.CharField(max_length=10, verbose_name='zipcode')),
                ('email', models.CharField(max_length=32, verbose_name='e-mail address')),
                ('phone', models.CharField(max_length=32, verbose_name='phone number')),
                ('FirstName', models.CharField(max_length=32, verbose_name='first name')),
                ('MiddleName', models.CharField(max_length=32, verbose_name='middle name')),
                ('LastName', models.CharField(max_length=32, verbose_name='last name')),
                ('InsuranceCompany', models.CharField(max_length=32, verbose_name='insurance company')),
                ('InsuranceNumber', models.CharField(max_length=10, verbose_name='insurance number')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coupon Rate')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
            ],
        ),
    ]
