# Generated by Django 4.0.4 on 2022-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualinfo',
            name='password',
            field=models.CharField(default='2022050413259412', max_length=64, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='individualinfo',
            name='username',
            field=models.CharField(default='2022050413254880', max_length=32, verbose_name='username'),
        ),
    ]
