# Generated by Django 4.0.4 on 2022-05-10 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_individualinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='password',
            field=models.CharField(default='2022050921136408', max_length=64, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='username',
            field=models.CharField(default='2022050921136813', max_length=32, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
                ('StartPoint', models.SmallIntegerField(choices=[(1, 'Washington'), (2, 'Idaho'), (3, 'Oregon'), (4, 'Montana'), (5, 'California'), (6, 'Nevada'), (7, 'Utah'), (8, 'Arizona'), (9, 'Wyoming'), (10, 'Colorado'), (11, 'New Mexcio'), (12, 'North Dakota')], verbose_name='Start Point')),
                ('EndPoint', models.SmallIntegerField(choices=[(1, 'Washington'), (2, 'Idaho'), (3, 'Oregon'), (4, 'Montana'), (5, 'California'), (6, 'Nevada'), (7, 'Utah'), (8, 'Arizona'), (9, 'Wyoming'), (10, 'Colorado'), (11, 'New Mexcio'), (12, 'North Dakota')], verbose_name='End Point')),
                ('distance', models.IntegerField(verbose_name='Distance')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.individualinfo')),
                ('VehicleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.vehicle')),
            ],
        ),
    ]
