# Generated by Django 4.0.4 on 2022-05-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_individualinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualinfo',
            name='password',
            field=models.CharField(default='2022051002155828', max_length=64, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='username',
            field=models.CharField(default='2022051002152698', max_length=32, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceDate', models.DateField(verbose_name='Invoice Date')),
                ('InvoiceAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invoice Amount')),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.order')),
            ],
        ),
    ]
