# Generated by Django 4.0.4 on 2022-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_individualinfo_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='PaymentAmount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Payment Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='password',
            field=models.CharField(default='2022051002517034', max_length=64, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='individualinfo',
            name='username',
            field=models.CharField(default='2022051002515173', max_length=32, verbose_name='username'),
        ),
    ]
