# Generated by Django 4.0.4 on 2022-05-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30, verbose_name='street')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('zipcode', models.CharField(max_length=6, verbose_name='zipcode')),
                ('phone', models.CharField(max_length=10, verbose_name='phone #')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Office',
            },
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=50, verbose_name='class type')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='daily rate for vehicle')),
                ('extra_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='extra rate for vehicle')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Class',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20, verbose_name='make')),
                ('model', models.CharField(max_length=20, verbose_name="vehicle's model")),
                ('make_year', models.DateField(verbose_name='made year')),
                ('VIN', models.CharField(max_length=10, verbose_name='Vehicle_Identification_Number')),
                ('LPN', models.CharField(max_length=10, verbose_name='License Plate Number')),
                ('slug', models.SlugField(max_length=1000)),
                ('office_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.officeinfo')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicleclass')),
            ],
        ),
    ]
